// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/adaptivetelemetry component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("adaptivetelemetry")
	ScopeName = "github.com/newrelic/nrdot-collector-components/processor/adaptivetelemetryprocessor"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
