name: build-and-test-arm
'on':
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  merge_group: null
  pull_request: null
env:
  TEST_RESULTS: testbed/tests/results/junit/results.xml
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  setup-environment:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && (!contains(github.event.pull_request.labels.*.name,
      'Skip ARM') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Install dependencies
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make -j2 gomoddownload
    - name: Install Tools
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make install-tools
  arm-unittest-matrix:
    needs:
    - setup-environment
    if: ${{ github.actor != 'dependabot[bot]' && (!contains(github.event.pull_request.labels.*.name,
      'Skip ARM') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    strategy:
      fail-fast: false
      matrix:
        group:
        - receiver
        - processor
        - exporter
        - extension
        - connector
        - internal
        - pkg
        - cmd
        - other
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Run Unit Tests
      id: tests
      if: github.ref != 'refs/heads/main'
      run: make -j2 gotest GROUP=${{ matrix.group }}
    - name: Run Unit Tests With JUnit and Coverage
      id: tests-with-junit
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      continue-on-error: true
      run: make gotest-with-junit-and-cover GROUP=${{ matrix.group }}
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: test-results-arm-${{ matrix.group }}
        path: internal/tools/testresults/
        retention-days: 4
    - name: Fail workflow if tests fails
      if: always()
      run: "if [[ \"${{ steps.tests-with-junit.outcome }}\" == \"failure\" || \"${{\
        \ steps.tests.outcome }}\" == \"failure\" ]]; then\n  echo \"Tests failed.\
        \ Failing workflow.\"\n  exit 1\nelse\n  echo \"Tests passed or were skipped.\
        \ Continuing.\"\nfi\n"
  arm-unittest:
    if: ${{ github.actor != 'dependabot[bot]' && (!contains(github.event.pull_request.labels.*.name,
      'Skip ARM') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    runs-on: ubuntu-24.04
    needs:
    - arm-unittest-matrix
    steps:
    - name: Print result
      run: echo ${{ needs.arm-unittest-matrix.result }}
    - name: Interpret result
      run: "if [[ success == ${{ needs.arm-unittest-matrix.result }} ]]\nthen\n  echo\
        \ \"All matrix jobs passed!\"\nelse\n  echo \"One or more matrix jobs failed.\"\
        \n  false\nfi\n"
  flakytests-generate-issues:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs:
    - arm-unittest-matrix
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
      with:
        merge-multiple: true
        pattern: test-results-arm-*
        path: ./internal/tools/testresults/
    - name: Generate Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'make install-tools

        ./.tools/issuegenerator -path ./internal/tools/testresults/ -labels "flaky
        tests,needs triage"

        '
