name: build-and-test-windows
'on':
  push:
    branches:
    - main
    - releases/**
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  merge_group: null
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled
    branches:
    - main
env:
  TEST_RESULTS: testbed/tests/results/junit/results.xml
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions: read-all
jobs:
  setup-environment:
    if: ${{ github.actor != 'dependabot[bot]' && (contains(github.event.pull_request.labels.*.name,
      'Run Windows') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    strategy:
      fail-fast: true
      matrix:
        os:
        - windows-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Install dependencies
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make -j2 gomoddownload
    - name: Install Tools
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make install-tools
  windows-smoke-build:
    needs:
    - setup-environment
    strategy:
      fail-fast: true
      matrix:
        os:
        - windows-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - run: ./.github/workflows/scripts/free-disk-space.sh
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Install dependencies
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make -j2 gomoddownload
    - name: Install Tools
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make install-tools
    - name: Generate nrdotcol files
      run: make gennrdotcol
    - name: Build Collector
      run: make nrdotcol
  windows-unittest-matrix:
    needs:
    - setup-environment
    strategy:
      fail-fast: false
      matrix:
        group:
        - receiver
        - processor
        - exporter
        - extension
        - connector
        - internal
        - pkg
        - cmd
        - other
        os:
        - windows-2025
        - windows-latest
    runs-on: ${{ matrix.os }}
    if: ${{ github.actor != 'dependabot[bot]' && (contains(github.event.pull_request.labels.*.name,
      'Run Windows') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    env:
      GOGC: 50
      GOMEMLIMIT: 2GiB
      CGO_ENABLED: ${{ matrix.os == 'windows-11-arm' && '0' || '' }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Ensure required ports in the dynamic range are available
      run: '& ${{ github.workspace }}\.github\workflows\scripts\win-required-ports.ps1

        '
    - name: Build shared test tools
      run: make "$(${PWD} -replace '\\', '/')/.tools/gotestsum"
    - name: Run Unit Tests
      id: tests
      if: github.ref != 'refs/heads/main'
      run: make -j2 gotest GROUP=${{ matrix.group }}
    - name: Run Unit Tests With JUnit and Coverage
      id: tests-with-junit
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      continue-on-error: true
      run: make gotest-with-junit-and-cover GROUP=${{ matrix.group }}
    - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        name: test-results-windows-${{ matrix.os }}-${{ matrix.group }}
        path: internal/tools/testresults/
        retention-days: 4
    - name: Fail workflow if tests fails
      if: always()
      shell: bash
      run: "if [[ \"${{ steps.tests-with-junit.outcome }}\" == \"failure\" || \"${{\
        \ steps.tests.outcome }}\" == \"failure\" ]]; then\n  echo \"Tests failed.\
        \ Failing workflow.\"\n  exit 1\nelse\n  echo \"Tests passed or were skipped.\
        \ Continuing.\"\nfi\n"
  windows-unittest:
    if: ${{ github.actor != 'dependabot[bot]' && (contains(github.event.pull_request.labels.*.name,
      'Run Windows') || github.event_name == 'push' || github.event_name == 'merge_group')
      }}
    runs-on: windows-latest
    needs:
    - windows-unittest-matrix
    steps:
    - name: Print result
      run: echo ${{ needs.windows-unittest-matrix.result }}
    - name: Interpret result
      shell: bash
      run: "if [[ success == ${{ needs.windows-unittest-matrix.result }} ]]\nthen\n\
        \  echo \"All matrix jobs passed!\"\nelse\n  echo \"One or more matrix jobs\
        \ failed.\"\n  false\nfi\n"
  flakytests-generate-issues:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        os:
        - windows-2025
        - windows-11-arm
    runs-on: ubuntu-24.04
    needs:
    - windows-unittest-matrix
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Install dependencies
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make -j2 gomoddownload
    - name: Install Tools
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make install-tools
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
      with:
        merge-multiple: true
        pattern: test-results-windows-${{ matrix.os }}-*
        path: ./internal/tools/testresults/
    - name: Generate Issues
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'make install-tools

        ./.tools/issuegenerator -path ./internal/tools/testresults/ -labels "flaky
        tests,needs triage"

        '
