name: codeowners
on:
  push:
    branches: [main]
    paths:
      - ".github/CODEOWNERS"
      - "**/metadata.yaml"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request_target:
    paths:
      - ".github/CODEOWNERS"
      - "**/metadata.yaml"
    types:
      - opened
      - synchronize
      - edited
      - reopened
env:
  # Make sure to exit early if cache segment download times out after 2 minutes.
  # We limit cache download as a whole to 5 minutes.
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check-codeowners:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    # SECURITY: Use github.event.pull_request.user.login instead of github.actor to prevent actor impersonation attacks
    # Additionally, ensure the PR is not from a fork to prevent execution of untrusted code with repo secrets
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' && github.repository == 'newrelic/nrdot-collector-components' && github.event.pull_request.head.repo.fork == false }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        id: go-setup
        with:
          go-version: oldstable
          cache-dependency-path: "**/*.sum"

      - name: Install tools
        run: |
          make install-tools

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          path: pr

      - name: Gen CODEOWNERS
        run: |
          cd pr
          GITHUB_TOKEN=${{ secrets.OTELCOMBOT_TOKEN }} ../.tools/githubgen --default-codeowner="@newrelic/otelcomm" --github-org="newrelic" codeowners
          git diff -s --exit-code || (echo 'Generated code is out of date, please run "make gencodeowners" or apply this diff and commit the changes in this PR.' && git diff && exit 1)
