name: scoped-test
'on':
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
permissions: read-all
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    env:
      PR_HEAD: ${{ github.event.pull_request.head.sha }}
    outputs:
      go_sources: ${{ steps.changes.outputs.go_sources }}
      go_tests: ${{ steps.changes.outputs.go_tests }}
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      with:
        fetch-depth: 0
    - name: Get changes
      shell: bash
      id: changes
      env:
        PR_HEAD: ${{ github.event.pull_request.head.sha }}
      run: "changed_files=\"$(git diff --name-only --diff-filter=ACMRTUXB \"$(git\
        \ merge-base origin/main \"$PR_HEAD\")\" \"$PR_HEAD\")\"\necho changed_files\n\
        echo \"$changed_files\"\n\ngo_sources=$(echo \"$changed_files\" | tr ' ' '\\\
        n' | grep -E '\\.go$' | grep -v -E '.*_test\\.go$' || true)\necho go_sources\n\
        echo \"$go_sources\"\nif [[ -n \"$go_sources\" ]]; then\n  {\n    echo 'go_sources<<EOF'\n\
        \    echo \"$go_sources\"\n    echo EOF\n  } >> \"$GITHUB_OUTPUT\"\nfi\n\n\
        go_tests=$(echo \"$changed_files\" | tr ' ' '\\n' | grep -E '.*_test\\.go$'\
        \ || true)\necho go_tests\necho \"$go_tests\"\nif [[ -n \"$go_tests\" ]];\
        \ then\n  {\n    echo 'go_tests<<EOF'\n    echo \"$go_tests\"\n    echo EOF\n\
        \  } >> \"$GITHUB_OUTPUT\"\nfi\n"
  scoped-tests-matrix:
    needs: changedfiles
    if: needs.changedfiles.outputs.go_sources != '' || needs.changedfiles.outputs.go_tests
      != ''
    strategy:
      matrix:
        runner:
        - windows-2022
        - windows-2025
        - windows-latest
        - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    env:
      CGO_ENABLED: ${{ matrix.runner == 'windows-11-arm' && '0' || '' }}
    steps:
    - name: Echo changed files
      shell: bash
      run: 'echo "go_sources: ${{ needs.changedfiles.outputs.go_sources }}"

        echo "go_tests: ${{ needs.changedfiles.outputs.go_tests }}"

        '
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      with:
        fetch-depth: 0
    - run: ./.github/workflows/scripts/free-disk-space.sh
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
      id: go-setup
      with:
        go-version: oldstable
        cache-dependency-path: '**/*.sum'
    - name: Install dependencies
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make -j2 gomoddownload
    - name: Install Tools
      if: steps.go-setup.outputs.cache-hit != 'true'
      run: make install-tools
    - name: Build gotestsum
      shell: bash
      run: make "$PWD/.tools/gotestsum"
    - name: Run changed tests
      if: needs.changedfiles.outputs.go_tests
      env:
        CHANGED_GOLANG_TESTS: ${{ needs.changedfiles.outputs.go_tests }}
      run: 'make run-changed-tests

        '
    - name: Run tests on dependent components
      if: needs.changedfiles.outputs.go_sources
      env:
        CHANGED_GOLANG_SOURCES: ${{ needs.changedfiles.outputs.go_sources }}
      run: 'make for-affected-components CMD="make lint test-twice"

        '
  scoped-tests:
    runs-on: ubuntu-24.04
    needs:
    - scoped-tests-matrix
    steps:
    - name: Print result
      run: echo ${{ needs.scoped-tests-matrix.result }}
    - name: Interpret result
      run: "if [[ success == ${{ needs.scoped-tests-matrix.result }} ]]\nthen\n  echo\
        \ \"All matrix jobs passed!\"\nelse\n  echo \"One or more matrix jobs failed.\"\
        \n  false\nfi\n"
